{
    "criteria": [
        {
            "criterion": "AllDocuments",
            "passed": true,
            "reason": "All documents pass."
        },
        {
            "criterion": "Domain",
            "passed": false,
            "reason": "Document source unavailable."
        },
        {
            "criterion": "QuestionAnswerStrings",
            "passed": true,
            "reason": "Text contains Q:."
        },
        {
            "criterion": "QuestionAnswerStringsV2",
            "passed": true,
            "reason": "Text contains ['Q:', 'A:']."
        },
        {
            "criterion": "FullyStructured",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamStrings",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamStringsV2",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamplesStrings",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ListPrefix",
            "passed": false,
            "reason": "Found 0 list prefixes. (Min: 5)"
        },
        {
            "criterion": "ListPrefixV2",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamplesMinimalEmbed",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamplesSynonymsEmbed",
            "passed": false,
            "reason": "Does not meet criterion."
        },
        {
            "criterion": "ExamplesDiverseEmbed",
            "passed": false,
            "reason": "Does not meet criterion."
        }
    ],
    "doc_id": "3019",
    "text": "Q:\n\norg.hibernate.exception.JDBCConnectionException: could not execute query using hibernate\n\nI've developed an application and it worked just fine locally , and when I uploaded it to a remote server it gave me com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException. I've tried the solution mentioned in the topic in this link :\nhttps://stackoverflow.com/questions/7565143/com-mysql-jdbc-exceptions-jdbc4-mysqlnontransientconnectionexception-no-operati#= \nhere is the code that has access to database:\n protected Number getCount(Class clazz){\n      Session currentSession = HibernateUtil.getSessionFactory().getCurrentSession();\n        Transaction transaction = currentSession.beginTransaction();\n      return (Number) currentSession.createCriteria(clazz).setProjection(Projections.rowCount()).uniqueResult();\n}\n\nand here is my hibernate configuration:\n<hibernate-configuration>\n<session-factory>\n<property name=\"hibernate.dialect\">org.hibernate.dialect.MySQLDialect</property>\n<property name=\"hibernate.connection.driver_class\">com.mysql.jdbc.Driver</property>\n<property name=\"hibernate.current_session_context_class\">thread</property>\n<property    name=\"hibernate.connection.url\">jdbc:mysql://localhost:3306/lyrics_db</property>\n<property name=\"hibernate.connection.username\">root</property>\n<property name=\"hibernate.connection.password\">123456</property>\n<property name=\"hibernate.hbm2ddl.auto\">update</property>\n<property name=\"hibernate.show_sql\">true</property>\n<property name=\"connection.provider_class\">org.hibernate.connection.C3P0ConnectionProvider</property>\n<property name=\"c3p0.acquire_increment\">1</property>\n<property name=\"c3p0.idle_test_period\">100</property>\n<!-- seconds -->\n<property name=\"c3p0.max_size\">100</property>\n<property name=\"c3p0.max_statements\">0</property>\n<property name=\"c3p0.min_size\">10</property>\n<property name=\"c3p0.timeout\">1800</property>\n<!-- seconds -->\n\n</session-factory>\n</hibernate-configuration>\n\nand it's not working and I'm getting the same exception , and here is my full stack trace:\nDec 3, 2013 8:02:44 PM org.apache.catalina.core.StandardWrapperValve invoke\nSEVERE: Servlet.service() for servlet ServletAdaptor threw exception\norg.hibernate.exception.JDBCConnectionException: could not execute query\nat org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:74)\nat org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)\nat org.hibernate.loader.Loader.doList(Loader.java:2223)\nat org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)\nat org.hibernate.loader.Loader.list(Loader.java:2099)\nat org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:94)\nat org.hibernate.impl.SessionImpl.list(SessionImpl.java:1569)\nat org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:283)\nat daos.UltimateDao.listWithLimitWithOrder(UltimateDao.java:47)\nat daos.LyricDao.getTopHundred(LyricDao.java:73)\nat com.xeeapps.service.Service.getTopHundred(Service.java:91)\nat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\nat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\nat        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\nat java.lang.reflect.Method.invoke(Method.java:597)\nat com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\nat com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)\nat com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\nat com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)\nat com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\nat com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)\nat com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)\nat com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)\nat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480)\nat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411)\nat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)\nat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)\nat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)\nat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)\nat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)\nat javax.servlet.http.HttpServlet.service(HttpServlet.java:717)\nat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\nat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\nat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\nat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\nat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\nat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\nat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\nat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\nat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\nat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\nat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\nat java.lang.Thread.run(Thread.java:662)\nCaused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.\nat sun.reflect.GeneratedConstructorAccessor127.newInstance(Unknown Source)\nat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)\nat java.lang.reflect.Constructor.newInstance(Constructor.java:513)\nat com.mysql.jdbc.Util.handleNewInstance(Util.java:411)\nat com.mysql.jdbc.Util.getInstance(Util.java:386)\nat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1014)\nat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988)\nat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974)\nat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)\nat com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1290)\nat com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1282)\nat com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4468)\nat com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4434)\nat com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:1076)\nat org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:505)\nat org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:423)\nat org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:139)\nat org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1547)\nat org.hibernate.loader.Loader.doQuery(Loader.java:673)\nat    org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)\nat org.hibernate.loader.Loader.doList(Loader.java:2220)\n... 40 more\nCaused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 38,056,253 milliseconds ago.  The last packet sent successfully to the server was 38,056,857 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.\nat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\nat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)\nat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)\nat java.lang.reflect.Constructor.newInstance(Constructor.java:513)\nat com.mysql.jdbc.Util.handleNewInstance(Util.java:411)\nat com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1117)\nat com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3871)\nat com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2484)\nat com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)\nat com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)\nat com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)\nat com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)\nat com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:144)\nat org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)\nat org.hibernate.loader.Loader.getResultSet(Loader.java:1787)\nat org.hibernate.loader.Loader.doQuery(Loader.java:674)\nat org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)\nat org.hibernate.loader.Loader.doList(Loader.java:2220)\nat org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)\nat org.hibernate.loader.Loader.list(Loader.java:2099)\nat org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:94)\nat org.hibernate.impl.SessionImpl.list(SessionImpl.java:1569)\nat org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:283)\nat org.hibernate.impl.CriteriaImpl.uniqueResult(CriteriaImpl.java:305)\nat daos.UltimateDao.get(UltimateDao.java:24)\nat daos.SongDao.getSong(SongDao.java:31)\nat daos.LyricDao.getLyricForSong(LyricDao.java:24)\nat com.xeeapps.service.Service.getLyricForASong(Service.java:82)\n... 32 more\nCaused by: java.net.SocketException: Broken pipe\nat java.net.SocketOutputStream.socketWrite0(Native Method)\nat java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)\nat java.net.SocketOutputStream.write(SocketOutputStream.java:136)\nat java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)\nat java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)\nat com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3852)\n... 53 more\nDec 3, 2013 8:02:44 PM org.apache.catalina.core.StandardWrapperValve invoke\nSEVERE: Servlet.service() for servlet Faces Servlet threw exception\ncom.sun.jersey.api.client.UniformInterfaceException: GET       http://localhost:8080/LyricsService/webresources/service/getTopHundred returned a response status of 500 Internal Server Error\nat com.sun.jersey.api.client.WebResource.handle(WebResource.java:686)\nat com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)\nat com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)\nat client.LyricsClient.getTopHundred(LyricsClient.java:71)\nat controllers.TopHundredController.init(TopHundredController.java:32)\nat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\nat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\nat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\nat java.lang.reflect.Method.invoke(Method.java:597)\nat org.apache.el.parser.AstValue.invoke(AstValue.java:191)\nat org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)\nat com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)\nat com.sun.faces.facelets.tag.jsf.core.DeclarativeSystemEventListener.processEvent(EventHandler.java:128)\nat javax.faces.component.UIComponent$ComponentSystemEventListenerAdapter.processEvent(UIComponent.java:2563)\nat javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)\nat javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)\nat com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2187)\nat com.sun.faces.application.ApplicationImpl.invokeComponentListenersFor(ApplicationImpl.java:2135)\nat com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:289)\nat com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:247)\nat com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:107)\nat com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)\nat com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)\nat javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)\nat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\nat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\nat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\nat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\nat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\nat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\nat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\nat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\nat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\nat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\nat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\nat java.lang.Thread.run(Thread.java:662)\n\nDoes anyone know why this exception keeps happening even I changed my configuration?\n\nA:\n\nI guess the problem was that I didn't commit the transaction , so it made some sort of lock.I figured this out from this topic:\nWhat happens if you don't commit transaction in a database (say SQL Server)\n\n"
}